import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/ui/header";
import Footer from "./_components/ui/footer";
import { Toaster } from "./_components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen flex-col">
          <div className="flex-1">{children}</div>
          <Footer />
        </div>

        <Toaster />

        {/*  <div className="flex h-screen flex-col">
          <Header />
          <div className="flex-1">{children}</div>
          <Footer />
        </div> */}
      </body>
    </html>
  );
}
